config/routes.rb
CShopping::Application.routes.draw do
  resources :posts

  resources :homes

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.slim
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.slim
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/_form.html.slim
= form_for @home do |f|
  - if @home.errors.any?
    #error_explanation
      h2 = "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"
      ul
        - @home.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/homes/_modal.html.slim
div id="myModal" class="modal hide"
  div class="modal-header"
    a class="close" data-dismiss="modal" ×
    h3 Modal header

  div class="modal-body"
    p Test of modal
    div class="progress progress-danger progress-striped active"
      div class="bar" style="width: 20%;"

  div class="modal-footer"
    a href="#" class="btn btn-primary" Save changes
    a href="#" class="btn" data-dismiss="modal" Close

app/views/homes/edit.html.slim
h1 Editing home

== render 'form'

= link_to 'Show', @home
'|
= link_to 'Back', homes_path

app/views/homes/index.html.slim
div class="hero-unit"
  h1 Compass Twitter Bootstrap Demo 

  p Quick demonstration on how to setup the compass twitter bootstrap gem with Rails 3.2

  p
   a class="btn btn-primary btn-large" href="https://github.com/vwall/Compass-Twitter-Bootstrap-Demo-App" <i class="icon-info-sign icon-white"></i> View Source &raquo;

div class="row"
  div class="span4"
    h2 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

    p
      a class="btn" data-toggle="modal" href="#myModal" Demo Modal

  div class="span4"
    h2 Heading

    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

    p
      a class="btn" href="#" View details &raquo;

  div class="span4"
    h2 Heading

    p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.

    p
      a class="btn" href="#" View details &raquo;

= render 'modal'

app/views/homes/new.html.slim
h1 New home

== render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.slim
p#notice = notice


= link_to 'Edit', edit_home_path(@home)
'|
= link_to 'Back', homes_path

app/views/layouts/_nav.html.slim
div class="navbar navbar-fixed-top"
  div class="navbar-inner"
    div class="container"
      a class="brand" Demo 
      ul class="nav"
        li class="active" = link_to 'Home', "#" 
        li = link_to 'Posts', posts_path
        li = link_to 'Another LInk', '#'
      ul class="nav pull-right"
        li = link_to 'Right Link', '#'

app/views/layouts/application.html.slim
doctype 5
html
  /[if lt IE 7]
    html.no-js.ie6.oldie lang="en"
  /[if IE 7]
    html.no-js.ie7.oldie lang="en"
  /[if IE 8]
    html.no-js.ie8.oldie lang="en"
  /[if gte IE 8]
    html.no-js lang="en"
  head
    title Rails Application
    meta charset="utf-8"
    meta name="keywords" content="template language"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    coffee:
      window.CShopping =
       Templates:
        mustache:{}

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = respond_include_tags
    = csrf_meta_tag


    /javascript:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28934979-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
   
  body
    /[if lt IE 7]
      p.chromeframe
        |You are using an outdated browser.
        a href="http://browsehappy.com/" Upgrade your browser today
        |or
        a href="http://www.google.com/chromeframe/?redirect=true" install Google Chrome Frame
        |to better experience this site.
    = render 'layouts/nav'
    div.container
      div.content
        == yield

app/views/posts/index.html.slim
div id="posts"

javascript:
    $(function() {
    // Blog is the app name
    window.router = new CShopping.Routers.PostsRouter({posts: #{@posts.to_json.html_safe}});
    Backbone.history.start();
    });